# Generated by Django 4.2.3 on 2023-09-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author_alter_post_timeposted'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion1', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='form',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
