# Generated by Django 4.2.3 on 2023-09-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tanya_delete_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanya',
            name='pertanyaan_1',
        ),
        migrations.AddField(
            model_name='tanya',
            name='a',
            field=models.CharField(choices=[('select1', 'a.expend energy, enjoy groups or'), ('select2', 'b.conserve energy, enjoy one-on-one')], default=1, max_length=128, verbose_name='pertanyaan 1'),
        ),
    ]
