# Generated by Django 4.2.3 on 2023-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_tanya_pertanyaan_1_tanya_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='tanya1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(choices=[('select1', 'a.expend energy, enjoy groups or'), ('select2', 'b.conserve energy, enjoy one-on-one')], default=1, max_length=128, verbose_name='pertanyaan 1')),
                ('b', models.CharField(choices=[('select1', 'a.more outgoing, think out loud or'), ('select2', 'b.more reserved, think to yourself')], default=1, max_length=128, verbose_name='pertanyaan 2')),
                ('c', models.CharField(choices=[('select1', 'a.seek many tasks, public activities, interaction with others'), ('select2', 'b.seek private, solitary activities with quiet to concentrate')], default=1, max_length=128, verbose_name='pertanyaan 3')),
                ('d', models.CharField(choices=[('select1', 'a.external, communicative, express yourself or'), ('select2', 'b.internal, reticent, keep to yourself')], default=1, max_length=128, verbose_name='pertanyaan 4')),
                ('e', models.CharField(choices=[('select1', 'a.active, initiate or'), ('select2', 'b.reflective, deliberate')], default=1, max_length=128, verbose_name='pertanyaan 5')),
            ],
        ),
        migrations.CreateModel(
            name='tanya2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(choices=[('select1', 'a.interpret literally or'), ('select2', 'b.look for meaning and possibilities')], default=1, max_length=128, verbose_name='pertanyaan 6')),
                ('g', models.CharField(choices=[('select1', 'a.practical, realistic, experiential or'), ('select2', 'b.imaginative, innovative, theoretical')], default=1, max_length=128, verbose_name='pertanyaan 7')),
                ('h', models.CharField(choices=[('select1', 'a.standard, usual, conventional or'), ('select2', 'b.different, novel, unique')], default=1, max_length=128, verbose_name='pertanyaan 8')),
                ('i', models.CharField(choices=[('select1', 'a.focus on here-and-now or'), ('select2', 'b.look to the future, global perspective, “big picture”')], default=1, max_length=128, verbose_name='pertanyaan 9')),
                ('j', models.CharField(choices=[('select1', 'a.facts, things, “what is” or'), ('select2', 'b.ideas, dreams, “what could be,” philosophical')], default=1, max_length=128, verbose_name='pertanyaan 10')),
            ],
        ),
        migrations.CreateModel(
            name='tanya3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(choices=[('select1', 'a.logical, thinking, questioning or'), ('select2', 'b.empathetic, feeling, accommodating')], default=1, max_length=128, verbose_name='pertanyaan 11')),
                ('l', models.CharField(choices=[('select1', 'a. candid, straight forward, frank or'), ('select2', 'b. tactful, kind, encouraging')], default=1, max_length=128, verbose_name='pertanyaan 12')),
                ('m', models.CharField(choices=[('select1', 'a.firm, tend to criticize, hold the line or'), ('select2', 'b.gentle, tend to appreciate, conciliate')], default=1, max_length=128, verbose_name='pertanyaan 13')),
                ('n', models.CharField(choices=[('select1', 'a.tough-minded, just or'), ('select2', 'b.tender-hearted, merciful')], default=1, max_length=128, verbose_name='pertanyaan 14')),
                ('o', models.CharField(choices=[('select1', 'a.matter of fact, issue-oriented or'), ('select2', 'b.sensitive, people-oriented, compassionate')], default=1, max_length=128, verbose_name='pertanyaan 15')),
            ],
        ),
        migrations.CreateModel(
            name='tanya4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(choices=[('select1', 'a. organized, orderly or'), ('select2', 'b. flexible, adaptable')], default=1, max_length=128, verbose_name='pertanyaan 16')),
                ('q', models.CharField(choices=[('select1', 'a. plan, schedule or'), ('select2', 'b. unplanned, spontaneous')], default=1, max_length=128, verbose_name='pertanyaan 17')),
                ('r', models.CharField(choices=[('select1', 'a.regulated, structured or'), ('select2', 'b.easygoing, “live” and “let live”')], default=1, max_length=128, verbose_name='pertanyaan 18')),
                ('s', models.CharField(choices=[('select1', 'a.preparation, plan ahead or'), ('select2', 'b.go with the flow, adapt as you go')], default=1, max_length=128, verbose_name='pertanyaan 19')),
                ('t', models.CharField(choices=[('select1', 'a.control, govern or'), ('select2', 'b.latitude, freedom')], default=1, max_length=128, verbose_name='pertanyaan 20')),
            ],
        ),
        migrations.DeleteModel(
            name='tanya',
        ),
    ]
